export const DOMAIN = import.meta.env.VITE_API_URL
export const ACCESS_TOKEN = 'access_token';
export const REFRESH_TOKEN = 'refresh_token';
export const USERS = 'users/'
export const REFRESH_USER =`${DOMAIN}${USERS}refresh-token/`
export const REGIONS = 'regions/'
export const PRODUCTS = 'products/'
export const CATEGORIES = 'categories/'
export const CART = 'buskets/'
export const COLORS = 'colors/'
export const MATERIALS = 'materials/'
export const BUSKETS = 'buskets/'
export const ORDERS = 'orders/'
export const MY_CASHBACK = 'my_cashback/'
export const MY_ADDRESS = 'my_addresses/'
export const CREATE_ADDRESS = 'create_address/'